"""Database infrastructure."""

from polymarket_trader.infra.db.models import (
    AccountSnapshotModel,
    AllocationModel,
    AuditEventModel,
    Base,
    DecisionRecordModel,
    FillModel,
    MarketModel,
    OrderModel,
    OrderbookSnapshotModel,
    OutboxEventModel,
    PositionModel,
)
from polymarket_trader.infra.db.persistence import DatabasePersistenceRepository
from polymarket_trader.infra.db.repositories import (
    AccountHistoryPoint,
    AccountSnapshotRepository,
    AllocationRepository,
    AuditEventRepository,
    BaseRepository,
    DecisionRecordRepository,
    FillRepository,
    MarketRepository,
    OrderRepository,
    OrderbookSnapshotRepository,
    OutboxEventRepository,
    PositionRepository,
    RepositoryPage,
)
from polymarket_trader.infra.db.session import build_engine, build_session_factory, initialize_database

__all__ = [
    "AccountHistoryPoint",
    "AccountSnapshotModel",
    "AccountSnapshotRepository",
    "AllocationModel",
    "AllocationRepository",
    "AuditEventModel",
    "AuditEventRepository",
    "Base",
    "BaseRepository",
    "DatabasePersistenceRepository",
    "DecisionRecordModel",
    "DecisionRecordRepository",
    "FillModel",
    "FillRepository",
    "MarketModel",
    "MarketRepository",
    "OrderModel",
    "OrderRepository",
    "OrderbookSnapshotModel",
    "OrderbookSnapshotRepository",
    "OutboxEventModel",
    "OutboxEventRepository",
    "PositionModel",
    "PositionRepository",
    "RepositoryPage",
    "build_engine",
    "build_session_factory",
    "initialize_database",
]
